const path = require("node:path");

/** @type {import('next').NextConfig} */
const RUN_JOB_RUNTIME_PACKAGES = [
  "@isaacs/cliui",
  "@pkgjs/parseargs",
  "agent-base",
  "ansi-regex",
  "ansi-styles",
  "asynckit",
  "axios",
  "balanced-match",
  "base64-js",
  "bignumber.js",
  "brace-expansion",
  "buffer-equal-constant-time",
  "call-bind-apply-helpers",
  "call-bound",
  "color-convert",
  "color-name",
  "combined-stream",
  "concat-map",
  "cross-spawn",
  "data-uri-to-buffer",
  "dayjs",
  "debug",
  "delayed-stream",
  "dunder-proto",
  "eastasianwidth",
  "ecdsa-sig-formatter",
  "emoji-regex",
  "es-define-property",
  "es-errors",
  "es-object-atoms",
  "es-set-tostringtag",
  "extend",
  "fetch-blob",
  "follow-redirects",
  "foreground-child",
  "form-data",
  "formdata-polyfill",
  "function-bind",
  "gaxios",
  "gcp-metadata",
  "get-intrinsic",
  "get-proto",
  "glob",
  "google-auth-library",
  "google-logging-utils",
  "gopd",
  "gtoken",
  "has-symbols",
  "has-tostringtag",
  "hasown",
  "https-proxy-agent",
  "is-fullwidth-code-point",
  "isexe",
  "jackspeak",
  "json-bigint",
  "jsonwebtoken",
  "jwa",
  "jws",
  "lodash.includes",
  "lodash.isboolean",
  "lodash.isinteger",
  "lodash.isnumber",
  "lodash.isplainobject",
  "lodash.isstring",
  "lodash.once",
  "lru-cache",
  "math-intrinsics",
  "mime-db",
  "mime-types",
  "minimatch",
  "minipass",
  "ms",
  "node-domexception",
  "node-fetch",
  "object-inspect",
  "package-json-from-dist",
  "path-key",
  "path-scurry",
  "proxy-from-env",
  "qs",
  "rimraf",
  "safe-buffer",
  "scmp",
  "semver",
  "shebang-command",
  "shebang-regex",
  "side-channel",
  "side-channel-list",
  "side-channel-map",
  "side-channel-weakmap",
  "signal-exit",
  "string-width",
  "string-width-cjs",
  "strip-ansi",
  "strip-ansi-cjs",
  "twilio",
  "url-template",
  "web-streams-polyfill",
  "which",
  "wrap-ansi",
  "wrap-ansi-cjs",
  "xmlbuilder",
  "yallist",
];

const nextConfig = {
  experimental: {
    externalDir: true, // permite importar ../services/*
  },
  outputFileTracingRoot: path.resolve(__dirname, ".."),
  outputFileTracingIncludes: {
    // Jobs ejecutados por /api/run (spawn de scripts fuera de control-tower)
    "/api/run": [
      "../scripts/**/*",
      "../resources/customValues/**/*",
      "../resources/config/**/*",
      "../services/**/*",
      ...RUN_JOB_RUNTIME_PACKAGES.map((pkg) => `./node_modules/${pkg}/**/*`),
    ],
  },
  turbopack: {
    resolveAlias: {
      "@": path.resolve(__dirname, "src"),
    },
  },
  webpack: (config) => {
    config.resolve = config.resolve || {};
    config.resolve.alias = config.resolve.alias || {};
    config.resolve.alias["@"] = path.resolve(__dirname, "src");
    return config;
  },
};

module.exports = nextConfig;
