import type { Metadata } from "next";
import "./globals.css";

const BRAND_ICON_PATH = "/delta-icon.svg";

export const metadata: Metadata = {
  title: "My Drip Nurse - Delta System",
  description: "Generated by Axel Castro & Devasks LLC",
  icons: {
    icon: BRAND_ICON_PATH,
    shortcut: BRAND_ICON_PATH,
    apple: BRAND_ICON_PATH,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>{children}</body>
    </html>
  );
}
